# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: >
  ...
future: true # Include posts with a date in the future
github_username: barkerproperty
highlighter: rouge
locale: en_AU
markdown: kramdown
# permalink: /:categories/:title
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
repository: barkerproperty/barkerproperty.com.au
social:
  name: Barker Property
  links:
    - https://github.com/barkerproperty
source: docs
title: Barker Property
tagline:
url: "https://www.barkerproperty.com.au" # the base hostname & protocol for your site
include: ["_pages"]
